package com.otitan.zbslzy.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.otitan.sclyyq.entity.Emergency;

import com.otitan.zbslzy.dao.EmergencyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig emergencyDaoConfig;

    private final EmergencyDao emergencyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        emergencyDaoConfig = daoConfigMap.get(EmergencyDao.class).clone();
        emergencyDaoConfig.initIdentityScope(type);

        emergencyDao = new EmergencyDao(emergencyDaoConfig, this);

        registerDao(Emergency.class, emergencyDao);
    }
    
    public void clear() {
        emergencyDaoConfig.clearIdentityScope();
    }

    public EmergencyDao getEmergencyDao() {
        return emergencyDao;
    }

}
